version: 2
jobs:
  one:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - echo 1
  two:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - echo 2
  three:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - echo 3
  four:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: npm install
      - run: npm test


workflows:
  version: 2
  build:
    jobs:
      - one
      - two
      - three
      - four