version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: npm install
      - run: npm test
  development:
    requires:
      - build
    steps:
      - checkout
      - run: node -v
      - run: echo "deploy to development!!!!"
  production:
    requires:
      - build
      - development
    steps:
      - checkout
      - run: echo "deploy to production!"


workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - development
      - production