version: 2
jobs:
  # building and testing
  build_test:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: npm install
      - run: npm test

  # development server deployment
  development:
    filters:
      branches:
        only:
          - development
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: echo "deployed to development server"

  # production server deployment
  production:
    filters:
      branches:
        only:
          - master
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: echo "deployed to production server"

workflows:
  version: 2
  dev_prod:
    jobs:
      - build_test
      - development:
          requires:
            - build_test
      - production:
          requires:
            - development