version: 2
jobs:
  # building and testing
  build_test:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: node -v
      - run: npm install
      - run: npm test

  # development server deployment
  development:
    environment:
      NODE_ENV: development
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: echo "deployed to" $NODE_ENV "server"

  # production server deployment
  production:
    environment:
      NODE_ENV: production
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: echo "deployed to" $NODE_ENV "server"

workflows:
  version: 2
  dev_prod:
    jobs:
      - build_test
      - development:
          requires:
            - build_test
          filters:
            branches:
              only:
                - development
      - production:
          requires:
            - build_test
          filters:
            branches:
              only:
                - master
